### ISSUE TITLE
Duplicated lines error when restarting containers

### ISSUE THREAD

**Issue by dlumbrer** [Bitergia/bitergia-analytics-odfe-kibana#10]
When the container of this image is restarted, the `docker-entrypoint` code is executed again, forcing to duplicate the lines that are inserted with `>>`.

For example, here: https://github.com/Bitergia/bitergia-analytics-odfe-kibana/blob/master/docker-entrypoint.sh#L103

This is the output of the error:

```
/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:173
  throw generateError(state, message);
  ^
YAMLException: duplicated mapping key at line 40, column 1:
    opendistro_security.basicauth.lo ... 
    ^
    at generateError (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at storeMappingPair (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:335:7)
    at readBlockMapping (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:1098:9)
    at composeNode (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:1525:3)
    at loadDocuments (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:1588:5)
    at load (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:1614:19)
    at Object.safeLoad (/usr/share/kibana/node_modules/js-yaml/lib/js-yaml/loader.js:1637:10)
    at readYaml (/usr/share/kibana/node_modules/@kbn/apm-config-loader/target/utils/read_config.js:27:38)
```

To fix this bug it's needed a check before inserting the line. If the line exists, replace it with the new one. 

---

Thanks to @zhquan for reporting the bug

**Comment by dlumbrer** [comment]
I submitted a PR to solve this bug (tested stopping and starting the container and restarting).

Please @sduenas , check it when you have time.

**Comment by dlumbrer** [comment]
PR updated using `sed` in the right way for our deployment.
